services:
  postgres:
    container_name: postgres-db
    image: postgres:17
    environment:
      POSTGRES_DB: $PG_DBNAME
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - "5432:5432"
    restart: always

  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  rlt_bot:
    container_name: rlt-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: $APP_NAME
      LOG_LEVEL: $LOG_LEVEL
      BOT_TOKEN: $BOT_TOKEN
      PG_HOST: $PG_HOST
      PG_PORT: $PG_PORT
      PG_USER: $PG_USER
      PG_PASSWORD: $PG_PASSWORD
      PG_DBNAME: $PG_DBNAME
      LLM_URL: $LLM_URL
      LLM_MODEL: $LLM_MODEL
    image: $APP_NAME:$APP_VERSION
    restart: always
    depends_on:
      - postgres
    command:
      ["sh", "-c", "alembic upgrade head && python3 src/srv.py"]

volumes:
  ollama_data:



